config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :contracts
  resources :batches

  resources :clients do
    resources :addresses
    resources :phones
  end
  resources :payments
  # , except: [:edit]
  get "payments/new_with_contract/:contract_id", to: "payments#new", as: :new_with_contract

  root "home#index"

  get "client_results", to: "clients#results", as: :client_results
  get "all_notifications", to: "home#all_notifications"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :client
  has_many :batches
  has_many :payments, dependent: :destroy

  attr_accessor :batches_selected
  # attr_accessor :batch_list

  validates_numericality_of :total_amount, :down_payment, :total_payments, :monthly_payment, greater_than: 0
  validates :total_amount, :total_payments, :down_payment, :first_payment, :monthly_payment, :signing_date, presence: true

  scope :order_by_date, -> { order(created_at: :asc) }
  scope :expired, -> { where("next_payment<=?", Date.current) }
  scope :order_by_expired, -> { order(next_payment: :asc) }
  scope :order_by_next, -> { order(next_payment: :asc) }

  # Callbacks
  before_destroy :reset_contract_in_batch
  # after_save :update_contract_in_batch, if: :changes_next_payment?

  def update_contract_in_batch
    Batch.reset_contract_id_in_batches(id)
    Batch.batch_contract_update(batches_selected, id)
  end

  def reset_contract_in_batch
    Batch.reset_contract_id_in_batches(id)
  end

  def changes_next_payment?
    # binding.prailsry
    !next_payment_changed?
  end

  def set_first_next_payment
    current_date = first_payment
    update_column(:next_payment, current_date)
  end

  def self.get_notifications
    self
    .joins("JOIN payments ON payments.contract_id = contracts.id")
    .expired
    .group(:id)
    .having("SUM(payments.amount) + contracts.down_payment != contracts.total_amount")
    .order_by_next
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: %i[show edit update destroy]
  # before_action :get_payments, only: %i[show]
  before_action :set_catalogs

  # GET /contracts or /contracts.json
  def index
    @pagy, @contracts = pagy(Contract.eager_load(:batches, :payments).all.order_by_expired)
  end

  # GET /contracts/1 or /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts or /contracts.json
  def create
    @contract = Contract.new(contract_params)
    set_batches_selected
    # get_all_batches

    respond_to do |format|
      if @contract.save
        @contract.set_first_next_payment
        @contract.update_contract_in_batch

        format.html { redirect_to contract_url(@contract), notice: "El contrato fue creado exitosamente." }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1 or /contracts/1.json
  def update
    respond_to do |format|
      set_batches_selected
      # get_all_batches

      if @contract.update(contract_params)
        @contract.update_contract_in_batch

        format.html { redirect_to contract_url(@contract), notice: "El contrato fue actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1 or /contracts/1.json
  def destroy
    @contract.destroy

    respond_to do |format|
      format.html { redirect_to contracts_url, notice: "El contrato fue eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contract
    @contract = Contract.find(params[:id])
  end

  def set_catalogs
    @batches = batches_allowed
    @clients = Client.active.all.order_by_name
  end

  def batches_allowed
    # binding.pry
    return Batch.allowed.order_by_block.order_by_lot if @contract.nil?

    Batch.allowed + @contract.batches.order_by_block.order_by_lot
    # @batches = Batch.allowed
    # @batches + @contract.batches unless @contract.nil?
  end

  def set_batches_selected
    @contract.batches_selected = params[:contract][:batch_id].reject(&:empty?).map(&:to_i)
  end

  # def get_payments
  #   @pagy, @contract.payments = pagy(@contract.payments)
  # end
  # def get_all_batches
  #   @contract.batch_list = Batch.all
  # end

  # Only allow a list of trusted parameters through.
  def contract_params
    params.require(:contract).permit(:total_amount, :total_payments, :comments, :client_id, :down_payment, :next_payment, :first_payment, :monthly_payment, :map, :map_date, :signing_date)
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_contract.html.erb
<div class="card">
  <div class="card-header" role="tab" id="headingOne">
    <h6 class="mg-b-0">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="tx-gray-800 transition">
        <h6 class="tx-info tx-bold m-2" >Informacion</h6>
      </a>
    </h6>
  </div>
  <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
    <div class="card-block pd-20">
      <div id="<%= dom_id contract %>">
        <div class="form-layout form-layout-7">
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>ID</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control" >
                <span><%=contract.id%></span>
              </div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Fecha de firma</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span class=""><%=contract.signing_date.nil? ? "No especificada" : contract.signing_date.strftime("%d-%m-%Y")%></span>
              </div>
            </div>
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Cliente</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <%=link_to contract.client do%>
                  <span><%="#{contract.client.first_name} #{contract.client.middle_name} #{contract.client.last_name}"%></span>
                <% end %>
              </div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Lotes</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <% if contract.batches.empty? %>
                  <span class="tx-danger">Sin lotes</span>
                <% else %>
                  <span>/</span>
                  <%contract.batches.order_by_block.order_by_lot.each do |batch|%>
                    <%=link_to batch do%>
                      <span><%=batch.uuid%></span>
                    <% end %>
                    <span>/</span>
                  <% end %>
                <% end %>
              </div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Monto Total</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span class="tx-primary tx-bold"><%=number_to_currency(contract.total_amount)%></span>
              </div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Pago mensual</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span class="tx-info tx-bold"><%=number_to_currency(contract.monthly_payment)%></span>
              </div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Enganche</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span class="tx-bold"><%=number_to_currency(contract.down_payment)%></span>
              </div>
            </div>
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Primer pago</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span class=""><%=contract.first_payment.strftime("%d-%m-%Y")%></span>
              </div>
            </div>
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Siguiente pago</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <% if Time.now<=contract.next_payment %>
                  <span class="tx-primary tx-bold"><%=contract.next_payment.strftime("%d-%m-%Y")%></span>
                <% else %>
                  <span class="tx-danger tx-bold"><%=contract.next_payment.strftime("%d-%m-%Y")%></span>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Pagos realizados</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span><%="#{contract.payments.length} de #{contract.total_payments}"%></span>
              </div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Total pagado</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <%
                  total_paid=contract.down_payment
                  contract.payments.each do |payment|
                  total_paid+=payment.amount
                  end
                %>
                <span class="tx-success tx-bold"><%=number_to_currency(total_paid)%></span>
              </div>
            </div>
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Adeudo total</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <%to_pay = contract.total_amount-total_paid %>
                <span class="tx-warning tx-bold"><%=number_to_currency(to_pay)%></span>
              </div>
            </div>
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Plano entregado</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span class= <%= contract.map==true ? "tx-success" : "tx-danger"%> >
                  <%= contract.map==true ? "Si" : "No"%>
                </span>
              </div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span>Comentarios</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span><%=contract.comments%></span>
              </div>
            </div>
            <!-- col-8 -->
          </div>
          <!-- col-8 -->
        </div>
        <!-- col-8 -->
      </div>
      <!-- row -->
    </div>
  </div>
</div>

app/views/contracts/_contract_index_table.html.erb
<th scope="row"><%=contract.id%></th>
<td><%=link_to contract.client do%>
    <span>
      <%="#{contract.client.first_name} #{contract.client.middle_name} #{contract.client.last_name} "%>
    </span>
  <% end %>
</td>
<td>
  <% if contract.batches.empty? %>
    <span class="tx-danger tx-bold">Sin lotes</span>
  <% else %>
    <span>/</span>
    <%contract.batches.order_by_block.order_by_lot.each do |batch|%>
      <%=link_to batch do%>
        <span><%=batch.uuid%></span>
      <% end %>
      <span>/</span>
    <% end %>
  <% end %>
</td>
<td><%="#{contract.payments.length} de #{contract.total_payments}"%></td>
<td class=<%=contract.next_payment <= Time.now ? "tx-danger tx-bold" : "tx-primary tx-bold"%>><%=contract.next_payment.strftime("%d-%m-%Y")%></td>
<td class="tx-primary tx-bold"><%=number_to_currency(contract.total_amount)%></td>
<td class="tx-bold"><%=number_to_currency(contract.down_payment)%></td>
<%total_paid=contract.down_payment
  contract.payments.each do |payment|
  total_paid+=payment.amount
  end%>
<td class="tx-success tx-bold"><%=number_to_currency(total_paid)%></td>
<%to_pay = contract.total_amount-total_paid %>
<td class="tx-warning tx-bold"><%=number_to_currency(to_pay)%></td>
<% if contract.map==true %>
  <td class="tx-success tx-bold">Si</td>
<% else %>
  <td class="tx-danger tx-bold">No</td>
<% end %>
<td class="d-flex align-items-top justify-content-center">
  <%= link_to contract, class:"btn btn-info" do%>
    <i class="fa fa-eye"></i>
    <span class="tx-white tx-bold"></span>
  <% end %>
  <%= link_to edit_contract_path(contract), class:"btn btn-warning" do%>
    <i class="fa fa-pencil"></i>
  <% end %>
  <%= link_to new_with_contract_path(contract.id), class:"btn btn-teal" do%>
    <i class="fa fa-money"></i>
    <span class="tx-white tx-bold">Añadir pago</span>
  <% end %>
</td>

app/views/contracts/_form.html.erb
<%= form_with(model: contract) do |form| %>
  <div class="row">
    <% if contract.errors.any? %>
      <div style="color: red">
        <h5><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h5>
        <ul>
          <% contract.errors.each do |error| %>
            <li class="col-sm-8 mg-t-10 mg-sm-t-0"><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="row mg-t-20">
    <%= form.label :signing_date, style: "display: block", class:"col-sm-4 form-control-label" do%>
      Fecha de firma <span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.date_field :signing_date,class:"form-control"%>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label :client, style: "display: block", class:"col-sm-4 form-control-label" do%>
      Cliente<span class="tx-danger">*</span>
    <%end%>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.select :client_id, @clients.collect { |c| [ "#{c.first_name.capitalize} #{c.middle_name.capitalize} #{c.last_name.capitalize}", c.id ] }, {:prompt => 'Select Client...'}, class:"form-control selectpicker border border-gray"%>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label :batch_id, style: "display: block", class:"col-sm-4 form-control-label" do%>
      Lotes<span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.select :batch_id,options_for_select(@batches.map { |b| [ b.uuid, b.id ] }, @contract.batches.pluck(:id)), {},multiple:true, class:"form-control selectpicker multiselect border border-gray bg-danger", id:"batch_selector" %>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label :total_amount, style: "display: block", class:"col-sm-4 form-control-label" do%>
      Monto total<span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :total_amount,class:"form-control", id:"amount", placeholder: "$0"%>
    </div>
  </div>
  <div class="row mg-t-20 mb-4">
    <%= form.label :down_payment, style: "display: block", class:"col-sm-4 form-control-label" do%>
      Enganche<span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :down_payment, class:"form-control", placeholder: "$0"%>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label :total_payments, style: "display: block", class:"col-sm-4 form-control-label" do%>
      Numero de pagos<span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :total_payments,class:"form-control"%>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label :monthly_payment, style: "display: block", class:"col-sm-4 form-control-label" do%>
      Pago mensual<span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :monthly_payment ,class:"form-control", placeholder: "$0"%>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label :first_payment, style: "display: block", class:"col-sm-4 form-control-label" do%>
      Fecha de primer pago <span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.date_field :first_payment,class:"form-control", :disabled =>contract.first_payment.nil? ? false : true%>
    </div>
  </div>
  <div class="d-flex mt-4">
    <%= form.label "Plano entregado", style: "display: block", class:"" %>
    <%= form.check_box :map, class:"form-check-input col-lg-9" do%>
    <% end %>
  </div>
  <div class="row mg-t-20">
    <%= form.label :Comentarios, style: "display: block" , class:"col-sm-4 form-control-label"%>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_area :comments,class:"form-control"%>
    </div>
  </div>
  <div class="row mg-t-10 d-flex justify-content-center">
    <div class="form-layout-footer mg-t-30 mt-2">
      <%= form.submit "Confirmar", :onclick => "return confirm('Desea resgistrar la información')", class:"btn btn-success"%>
    </div>
    </div>
  <% end %>

app/views/contracts/_payments_table.html.erb
<td> <%=payment.file_number%> </td>
<td><%= payment.realization_date.nil? ? "No especificado" : payment.realization_date.strftime("%d-%m-%Y")%></td>
<th scope="row"><%=payment.date.strftime("%d-%m-%Y")%></th>
<td class= <%=payment.kind=="Completo"? "tx-success tx-bold" : "tx-warning tx-bold"%> > <%=payment.kind%> </td>
<td> <%=number_to_currency(payment.amount)%> </td>
<td class="d-flex align-items-top justify-content-center">
  <%= link_to payment, class:"btn btn-info" do%>
    <i class="fa fa-eye"></i>
    <span class="tx-white tx-bold"></span>
  <% end %>
  <!--
  <%= link_to edit_payment_path(payment), class:"btn btn-warning" do%>
    <i class="fa fa-pencil"></i>
  <% end %>
  -->
</td>

app/views/contracts/edit.html.erb
<div class="mg-t-80">
  <div class="col-xl-6">
    <div class="form-layout form-layout-4">
      <div class="pd-10 mg-t-20 bg-info mb-4 d-flex justify-content-between">
        <div class="nav nav-white-800 flex-column flex-md-row" role="tablist">
          <h6 class="tx-white m-2 tx-bold" >Edición de contrato <%=@contract.id%> </h6>
        </div>
        <div>
          <%= link_to contracts_path, class:"btn btn-primary" do%>
            <i class="fa fa-reply"></i>
          <% end %>
        </div>
      </div>
      <%= render "form", contract: @contract %>
    </div>
  </div>
  <!-- row -->
</div>
<br>

app/views/contracts/index.html.erb
<div class="bd rounded pd-10">
  <h1 class="tx-bold d-flex justify-content-center">CONTRATOS</h1>
  <div class="row d-flex justify-content-end m-3">
    <div class="d-flex align-items-center">
      <%= link_to new_contract_path, class:"btn btn-success tx-11 tx-uppercase tx-spacing tx-bold bd d-flex align-items-center pd-15" do%>
        <i class="fa fa-plus"></i>
      <% end %>
    </div>
  </div>
  <div id="contracts" class="bd bd-gray-300 rounded table-responsive">
    <table class="table table-bordered mg-b-0">
      <thead>
        <tr>
          <th class="bg-info"><span class="tx-white">ID</span></th>
          <th class="bg-info"><span class="tx-white">Cliente</span></th>
          <th class="bg-info"><span class="tx-white">Lotes</span></th>
          <th class="bg-info"><span class="tx-white">Pagos totales</span></th>
          <th class="bg-info"><span class="tx-white">Siguiente Pago</span></th>
          <th class="bg-info"><span class="tx-white">Monto Total</span></th>
          <th class="bg-info"><span class="tx-white">Enganche</span></th>
          <th class="bg-info"><span class="tx-white">Total pagado</span></th>
          <th class="bg-info"><span class="tx-white">Adeudo total</span></th>
          <th class="bg-info"><span class="tx-white">Plano entregado</span></th>
          <th class="bg-info"><span class="tx-white">Opciones</span></th>
        </tr>
      </thead>
      <tbody>
        <% @contracts.each do |contract| %>
          <tr>
            <%=render "contracts/contract_index_table", contract:contract %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <%=render "layouts/pagy/pagy"%>
  </div>
</div>

app/views/contracts/new.html.erb
<div class="mg-t-80">
  <div class="col-xl-6">
    <div class="form-layout form-layout-4">
      <div class="pd-10 mg-t-20 bg-info mb-4 d-flex justify-content-between">
        <div class="nav nav-white-800 flex-column flex-md-row" role="tablist">
          <h6 class="tx-white m-2 tx-bold" >Nuevo Contrato</h6>
        </div>
        <div>
          <%= link_to contracts_path, class:"btn btn-primary" do%>
            <i class="fa fa-reply"></i>
          <% end %>
        </div>
      </div>
      <%= render "form", contract: @contract %>
    </div>
  </div>
  <!-- row -->
</div>
<br>

app/views/contracts/show.html.erb
<div class="pd-10 mg-t-20 bg-info d-lg-flex justify-content-between">
  <div class="d-lg-flex align-items-center" role="tablist">
    <h5 class="tx-white m-2 tx-bold" >Contrato <%=@contract.id%></h5>
  </div>
  <div class="d-lg-flex">
    <div>
      <%= link_to contracts_path, class:"btn btn-primary" do%>
        <i class="fa fa-reply"></i>
      <% end %>
    </div>
    <%= link_to new_with_contract_path(@contract.id), class:"btn btn-teal" do%>
      <i class="fa fa-money"></i>
      <span class="tx-white tx-bold">Añadir pago</span>
    <% end %>
    <div class="btn-group ">
      <button type="button" class="btn btn-purple btn-block mg-b-10 dropdown-toggle tx-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-navicon"></i>
        <span class="tx-white">Opciones</span>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <div class="dropdown-item">
          <%= link_to edit_contract_path(@contract), class:"" do%>
            <i class="fa fa-pencil"></i>
            <span class="tx-bold">Editar contrato</span>
          <% end %>
        </div>
        <div class="dropdown-divider"></div>
        <div class="dropdown-item">
          <%= button_to @ccontract, method: :delete, :onclick => "return confirm('Desea elimninar este contrato de manera permanente')", class:"btn btn-danger btn-block mg-b-10" do%>
            <i class="icon ion-close"></i>
            <span class="tx-bold">Eliminar contrato</span>
          <% end %>
        </div >
      </div>
    </div>
  </div>
</div>
<div id="accordion" class="accordion" role="tablist" aria-multiselectable="true">
  <%= render @contract %>
</div>
<br>
<br>
<div class="pd-10 mg-t-20 bg-info d-lg-flex">
  <div class="d-lg-flex align-items-center" role="tablist">
    <h5 class="tx-white m-2 tx-bold" >Lista de pagos</h5>
  </div>
</div>
<div class="bd rounded table-responsive">
  <table class="table table-bordered mg-b-0">
    <thead>
      <tr>
        <th class="bg-secondary"><span class="tx-white">Folio</span> </th>
        <th class="bg-secondary"><span class="tx-white">Fecha a de realización</span> </th>
        <th class="bg-secondary"><span class="tx-white">Fecha a la que corresponede</span> </th>
        <th class="bg-secondary"><span class="tx-white">Tipo</span> </th>
        <th class="bg-secondary"><span class="tx-white">Monto</span> </th>
        <th class="bg-secondary"><span class="tx-white">Opciones</span> </th>
      </tr>
    </thead>
    <tbody>
      <%descending = -1%>
      <%@contract.payments.order_by_file_number_desc.each do |payment|%>
        <tr>
          <%=render "payments_table", payment:payment%>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div>
</div>