config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :contracts
  resources :batches

  resources :clients do
    resources :addresses
    resources :phones
  end
  resources :payments
  # , except: [:edit]
  get "payments/new_with_contract/:contract_id", to: "payments#new", as: :new_with_contract

  root "home#index"

  get "client_results", to: "clients#results", as: :client_results
  get "all_notifications", to: "home#all_notifications"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  SEARCH_COLUMNS = %w[id first_name middle_name last_name status]

  include Searchable

  has_many :phones, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :contracts

  validates :first_name, :middle_name, :last_name, presence: true

  scope :active, -> { where("status=true") }
  scope :order_by_name, -> { order(first_name: :asc) }
  scope :order_by_active, -> { order(status: :desc) }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, :set_catalogs, only: %i[show edit update destroy]
  # before_action :set_catalogs, only: %i[new edit create]

  # GET /clients or /clients.json
  def index
    @pagy, @clients = pagy(Client.all.order_by_active.order_by_name)
  end

  # GET /clients/1 or /clients/1.json
  def show
    @contracts = @client.contracts.order_by_date
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "El cliente fue creado exitosamente." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "El cliente fue actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "El cliente fue eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  def results
    @value = params[:value].downcase
    @error = false
    if @value.empty? || @value.length < 3 || @value.nil?
      @error = true
    else
      @results = Client.search(Client::SEARCH_COLUMNS, @value)
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.eager_load(:phones, :addresses).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def client_params
    params.require(:client).permit(:first_name, :middle_name, :last_name, :status, :email)
  end
end

def set_catalogs
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_addresses.html.erb
<div class="card">
  <div class="card-header" role="tab" id="headingThree">
    <h6 class="mg-b-0">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree" class="tx-gray-800 transition">
        <h6 class="tx-info tx-bold m-2" >Direcciones</h6>
      </a>
    </h6>
  </div>
  <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
    <div class="card-block pd-20">
      <p>
        <% if client.addresses.empty?%>
          <p class="tx-bold">Sin direcciones registradas</p>
        <%else%>
          <div class="form-layout form-layout-7">
            <%client.addresses.each_with_index do |address,index| %>
              <div class="pd-5 bg-info mt-1 d-flex align-items-center justify-content-between">
                <div class="tx-white m-2 tx-bold">
                  <%="Dirección N. #{index+1}"%>
                </div>
                <div class="btn-group ">
                  <button type="button" class="btn btn-purple btn-block mg-b-10 dropdown-toggle tx-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-navicon"></i>
                    <span class="tx-white">Opciones</span>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <div class="dropdown-item">
                      <%= link_to client_address_path(@client,address), class:"" do%>
                        <i class="fa fa-eye"></i>
                        <span class="tx-bold">Ver</span>
                      <% end %>
                    </div>
                    <div class="dropdown-item">
                      <%= link_to edit_client_address_path(@client,address), class:"" do%>
                        <i class="icon ion-edit"></i>
                        <span class="tx-bold">Editar</span>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row no-gutters ">
                <div class="col-5 col-sm-4">
                  <span class="tx-bold">Calle</span>
                </div>
                <!-- col-4 -->
                <div class="col-7 col-sm-8">
                  <div class="form-control" >
                    <span><%=address.street%></span></div>
                </div>
                <!-- col-8 -->
              </div>
              <div class="row no-gutters">
                <div class="col-5 col-sm-4">
                  <span class="tx-bold">Manzana</span>
                </div>
                <!-- col-4 -->
                <div class="col-7 col-sm-8">
                  <div class="form-control" >
                    <span><%=address.block%></span></div>
                </div>
                <!-- col-8 -->
              </div>
              <div class="row no-gutters">
                <div class="col-5 col-sm-4">
                  <span class="tx-bold">Lote</span>
                </div>
                <!-- col-4 -->
                <div class="col-7 col-sm-8">
                  <div class="form-control" >
                    <span><%=address.lot%></span></div>
                </div>
                <!-- col-8 -->
              </div>
              <div class="row no-gutters">
                <div class="col-5 col-sm-4">
                  <span class="tx-bold">Colonia</span>
                </div>
                <!-- col-4 -->
                <div class="col-7 col-sm-8">
                  <div class="form-control" >
                    <span><%=address.colony%></span></div>
                </div>
                <!-- col-8 -->
              </div>
              <div class="row no-gutters">
                <div class="col-5 col-sm-4">
                  <span class="tx-bold">Código Postal</span>
                </div>
                <!-- col-4 -->
                <div class="col-7 col-sm-8">
                  <div class="form-control" >
                    <span><%=address.postal_code%></span></div>
                </div>
                <!-- col-8 -->
              </div>
              <div class="row no-gutters">
                <div class="col-5 col-sm-4">
                  <span class="tx-bold">Ciudad</span>
                </div>
                <!-- col-4 -->
                <div class="col-7 col-sm-8">
                  <div class="form-control" >
                    <span><%=address.city%></span></div>
                </div>
                <!-- col-8 -->
              </div>
              <div class="row no-gutters">
                <div class="col-5 col-sm-4">
                  <span class="tx-bold">Estado</span>
                </div>
                <!-- col-4 -->
                <div class="col-7 col-sm-8">
                  <div class="form-control" >
                    <span><%=address.state%></span></div>
                </div>
                <!-- col-8 -->
              </div>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/clients/_client.html.erb
<div class="card">
  <div class="card-header" role="tab" id="headingOne">
    <h6 class="mg-b-0">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="tx-gray-800 transition">
        <h6 class="tx-info tx-bold m-2" >Información personal</h6>
      </a>
    </h6>
  </div>
  <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
    <div class="card-block pd-20">
      <div id="<%= dom_id client %>">
        <div class="form-layout form-layout-7">
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span class="tx-bold">Nombre</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span><%=client.first_name%></span></div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span class="tx-bold">Apellido paterno</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span><%=client.middle_name%></span></div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4">
              <span class="tx-bold">Apellido materno</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span><%=client.last_name%></span></div>
            </div>
            <!-- col-8 -->
          </div>
          <div class="row no-gutters">
            <div class="col-5 col-sm-4 d-flex">
              <span class="tx-bold mg-1 d-flex">E-mail</span>
            </div>
            <!-- col-4 -->
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <%if client.email.nil?%>
                  <span class="">No especificado</span></div>
              <% else %>
                <span><%=client.email%></span></div>
            <% end %>
          </div>
          <!-- col-8 -->
        </div>
        <div class="row no-gutters">
          <div class="col-5 col-sm-4">
            <span class="tx-bold">Estado</span>
          </div>
          <!-- col-4 -->
          <% if client.status==true %>
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span class="tx-primary tx-bold">Activo</span>
              </div>
            </div>
          <% else %>
            <div class="col-7 col-sm-8">
              <div class="form-control">
                <span class="tx-danger tx-bold">Inactivo</span>
              </div>
            </div>
          <% end %>
        </div>
        <!-- col-8 -->
      </div>
      <!-- col-8 -->
    </div>
    <!-- row -->
    <!-- card-header -->
  </div>
</div>
</div>

app/views/clients/_client_index_table.html.erb
<td><%= client.first_name%></td>
<td><%= client.middle_name%></td>
<td><%= client.last_name%></td>
<td><% if client.status==true %>
    <span class="tx-primary">Activo</span>
  <% else %>
    <span class="tx-danger">Inactivo</span>
  <% end %>
</td>
<td class="d-flex align-items-top justify-content-center">
  <%= link_to client, class:"btn btn-info" do%>
    <i class="fa fa-eye"></i>
    <span class="tx-white tx-bold"></span>
  <% end %>
  <%= link_to edit_client_path(client), class:"btn btn-warning" do%>
    <i class="fa fa-pencil"></i>
  <% end %>
</td>

app/views/clients/_contracts_table.html.erb
<th scope="row"><%=contract.id%></th>
<td>
  <% if contract.batches.empty? %>
    <span class="tx-danger tx-bold">Sin lotes</span>
  <% else %>
    <span>/</span>
    <%contract.batches.order_by_block.order_by_lot.each do |batch|%>
      <%=link_to batch do%>
        <span><%=batch.uuid%></span>
      <% end %>
      <span>/</span>
    <% end %>
  <% end %>
</td>
<td><%="#{contract.payments.length} de #{contract.total_payments}"%></td>
<td class=<%=contract.next_payment <= Time.now ? "tx-danger tx-bold" : "tx-primary tx-bold"%>><%=contract.next_payment.strftime("%d-%m-%Y")%></td>
<td class="tx-primary tx-bold"><%=number_to_currency(contract.total_amount)%></td>
<td class="tx-bold"><%=number_to_currency(contract.down_payment)%></td>
<%total_paid=contract.down_payment
  contract.payments.each do |payment|
  total_paid+=payment.amount
  end%>
<td class="tx-success tx-bold"><%=number_to_currency(total_paid)%></td>
<%to_pay = contract.total_amount-total_paid %>
<td class="tx-warning tx-bold"><%=number_to_currency(to_pay)%></td>
<td class=  <%=contract.map == true ? "tx-success tx-bold" : "tx-danger tx-bold" %>><%=contract.map == true ? "Si" : "No"%></td>
<td class="d-flex align-items-top justify-content-center">
  <%= link_to contract, class:"btn btn-info" do%>
    <i class="fa fa-eye"></i>
    <span class="tx-white tx-bold"></span>
  <% end %>
  <%= link_to edit_contract_path(contract), class:"btn btn-warning" do%>
    <i class="fa fa-pencil"></i>
  <% end %>
  <%= link_to new_with_contract_path(contract.id), class:"btn btn-teal" do%>
    <i class="fa fa-money"></i>
    <span class="tx-white tx-bold">Añadir pago</span>
  <% end %>
</td>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <%= form.label :first_name, style: "display: block", class:"col-sm-4 form-control-label" do %>
      Nombre <span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :first_name,class:"form-control"%>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label :middle_name, style: "display: block", class:"col-sm-4 form-control-label" do %>
      Apellido paterno <span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :middle_name,class:"form-control"%>
    </div>
  </div>
  <div class="row mg-t-20 mb-4">
    <%= form.label :last_name, style: "display: block", class:"col-sm-4 form-control-label" do %>
      Apellido materno <span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :last_name,class:"form-control"%>
    </div>
  </div>
  <div class="row mg-t-20 mb-4">
    <%= form.label :email, style: "display: block", class:"col-sm-4 form-control-label" do %>
      Correo Electronico
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :email ,class:"form-control"%>
    </div>
  </div>
  <div class="d-flex">
    <%= form.label "Activo", style: "display: block", class:"" %>
    <%= form.check_box :status, class:"form-check-input col-lg-8" do%>
    <% end %>
  </div>
  <div class="row mg-t-10 d-flex justify-content-center">
    <div class="form-layout mg-t-30 mt-2">
      <%= form.submit "Confirmar", :onclick => "return confirm('Desea resgistrar la información')", class:"btn btn-success"%>
    </div>
  </div>
<% end %>

app/views/clients/_phones.html.erb
<div class="card">
  <div class="card-header" role="tab" id="headingTwo">
    <h6 class="mg-b-0">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" class="tx-gray-800 transition">
        <h6 class="tx-info tx-bold m-2" >Teléfonos</h6>
      </a>
    </h6>
  </div>
  <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
    <div class="card-block pd-20">
      <% if client.phones.empty?%>
        <p class="tx-bold">Sin teléfonos registrados</p>
      <%else%>
        <div class="form-layout form-layout-7">
          <%client.phones.each_with_index do |phone, index| %>
            <div class="row no-gutters">
              <div class="col-5 col-sm-4">
                <span class="tx-bold"><%=index + 1%></span>
              </div>
              <!-- col-4 -->
              <div class="col-7 col-sm-8">
                <div class="form-control" >
                  <%= link_to client_phone_path(client,phone) do %>
                    <span><%=phone.number%></span>
                  </div>
                <% end %>
              </div>
              <!-- col-8 -->
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/_search.html.erb
<%=form_tag( client_results_path, method: :get, name:"search_form", class:"") do%>
  <div class="d-lg-flex">
    <div>
      <input type="text" name="value" id="value" minlength="3" class="form-control" placeholder="Buscar..."/>
    </div>
    <div>
      <input type="submit" value="Buscar" class="btn btn-info tx-11 pd-y-12 tx-uppercase tx-spacing-2 tx-bold"/>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="mg-t-80">
  <div class="col-xl-6">
    <div class="form-layout form-layout-4">
      <div class="pd-10 mg-t-20 bg-info mb-4 d-flex justify-content-between">
        <div class="nav nav-white-800 flex-column flex-md-row" role="tablist">
          <h6 class="tx-white m-2 tx-bold" >Edición de cliente <%=" #{@client.first_name} #{@client.middle_name} #{@client.last_name}"%></h6>
        </div>
        <div>
          <%= link_to clients_path, class:"btn btn-primary" do%>
            <i class="fa fa-reply"></i>
          <% end %>
        </div>
      </div>
      <%= render "form", client: @client %>
    </div>
  </div>
  <!-- row -->
</div>
<br>

app/views/clients/index.html.erb
<div class="bd rounded pd-10">
  <h1 class="tx-bold d-flex justify-content-center">CLIENTES</h1>
  <div class="row d-lg-flex justify-content-end m-3 pd-10 rounded">
    <div class="d-flex mr-lg-3">
      <%=render "search"%>
    </div>
    <div class="d-flex align-items-center">
      <%= link_to new_client_path, class:"btn btn-success tx-11 tx-uppercase tx-spacing tx-bold bd d-flex align-items-center pd-15" do%>
        <i class="fa fa-plus"></i>
      <% end %>
    </div>
  </div>
  <div id="clients" class="bd bd-gray-300 rounded table-responsive">
    <table class="table table-bordered mg-b-0">
      <thead>
        <tr>
          <th class="bg-info"><span class="tx-white">Nombre</span></th>
          <th class="bg-info"><span class="tx-white">Apellido Paterno</span></th>
          <th class="bg-info"><span class="tx-white">Apellido Materno</span></th>
          <th class="bg-info"><span class="tx-white">Estado</span></th>
          <th class="bg-info"><span class="tx-white">Opciones</span></th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <%=render "clients/client_index_table", client:client %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <%=render "layouts/pagy/pagy"%>
  </div>
</div>

app/views/clients/new.html.erb
<div class="mg-t-80">
  <div class="col-xl-6">
    <div class="form-layout form-layout-4">
      <div class="pd-10 mg-t-20 bg-info mb-4 d-flex justify-content-between">
        <div class="nav nav-white-800 flex-column flex-md-row" role="tablist">
          <h6 class="tx-white m-2 tx-bold" >Nuevo Cliente</h6>
        </div>
        <div>
          <%= link_to clients_path, class:"btn btn-primary" do%>
            <i class="fa fa-reply"></i>
          <% end %>
        </div>
      </div>
      <%= render "form", client: @client %>
    </div>
  </div>
  <!-- row -->
</div>
<br>

app/views/clients/results.html.erb
<h1>Resultados</h1>
<div>
  <%= link_to clients_path, class:"btn btn-primary" do%>
    <i class="fa fa-reply"></i>
  <% end %>
</div>
<br>
<%=render "search"%>
<%unless @value.empty?%>
  <br>
  <br>
  <h5>Resultados para: &nbsp;<span class="tx-success"> "<%=@value%>"</span></h5>
  <br>
  <br>
  <% unless @error %>
    <% unless @results.empty?%>
      <%new_results = @results.uniq%>
      <%new_results.each_with_index do |result, index|%>
        <%=link_to result, class:"tx-bold" do%>
          <span><%="#{index+1}.-  #{result.first_name} #{result.middle_name} #{result.last_name}"%></span><br>
        <% end %>
      <% end %>
    <% else %>
      <span class="tx-danger tx-bold"><%="No hay ninguna coincidencia"%></span>
    <% end %>
  <% end %>
<% else %>
  <br>
  <br>
  <span class="tx-bold tx-danger">* Para obtener resutaldos, escriba un criterio de busqueda con mas de 3 caracteres</span>
<% end %>

app/views/clients/show.html.erb
<div class="pd-10 mg-t-20 bg-info d-lg-flex justify-content-between">
  <div class="d-lg-flex align-items-center" role="tablist">
    <h5 class="tx-white m-2 tx-bold" ><%="Información de cliente No. #{@client.id}"%></h5>
  </div>
  <div class="d-lg-flex">
    <div>
      <%= link_to clients_path, class:"btn btn-primary" do%>
        <i class="fa fa-reply"></i>
      <% end %>
    </div>
    <div class="btn-group ">
      <button type="button" class="btn btn-purple btn-block mg-b-10 dropdown-toggle tx-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-navicon"></i>
        <span class="tx-white">Opciones</span>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <div class="dropdown-item">
          <%= link_to edit_client_path(@client), class:"" do%>
            <i class="fa fa-pencil"></i>
            <span class="tx-bold">Editar cliente</span>
          <% end %>
        </div>
        <div class="dropdown-item">
          <%= link_to new_client_phone_path(@client), class:"" do%>
            <i class="fa fa-phone"></i>
            <span class="tx-bold">Agregar teléfono</span>
          <% end %>
        </div>
        <div class="dropdown-item">
          <%= link_to new_client_address_path(@client), class:"" do%>
            <i class="fa fa-home"></i>
            <span class="tx-bold">Agregar dirección</span>
          <% end %>
        </div>
        <div class="dropdown-divider"></div>
        <div class="dropdown-item">
          <%= button_to @client, method: :delete, :onclick => "return confirm('Desea eliminar este cliente de manera permanente')", class:"btn btn-danger btn-block mg-b-10" do%>
            <i class="icon ion-close"></i>
            <span class="tx-bold">Eliminar</span>
          <% end %>
        </div >
      </div>
    </div>
  </div>
</div>
<div id="accordion" class="accordion" role="tablist" aria-multiselectable="true">
  <%=render @client%>
  <%=render "/clients/phones", client: @client%>
  <%=render "/clients/addresses", client:@client%>
  <br>
  <br>
</div>
<div class="pd-10 mg-t-20 bg-info d-lg-flex">
  <div class="d-lg-flex align-items-center" role="tablist">
    <h5 class="tx-white m-2 tx-bold" >Contratos</h5>
  </div>
</div>
<div class="bd rounded table-responsive">
  <table class="table table-bordered mg-b-0">
    <thead>
      <tr>
        <th class="bg-secondary"><span class="tx-white">ID</span></th>
        <th class="bg-secondary"><span class="tx-white">Lotes</span></th>
        <th class="bg-secondary"><span class="tx-white">Pagos totales</span></th>
        <th class="bg-secondary"><span class="tx-white">Siguiente Pago</span></th>
        <th class="bg-secondary"><span class="tx-white">Monto Total</span></th>
        <th class="bg-secondary"><span class="tx-white">Enganche</span></th>
        <th class="bg-secondary"><span class="tx-white">Total pagado</span></th>
        <th class="bg-secondary"><span class="tx-white">Adeudo total</span></th>
        <th class="bg-secondary"><span class="tx-white">Plano entregado</span></th>
        <th class="bg-secondary"><span class="tx-white">Opciones</span></th>
      </tr>
    </thead>
    <tbody>
      <%@contracts.each do |contract|%>
        <tr>
          <%=render "contracts_table", contract:contract%>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<!-- bd-0 -->