config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :contracts
  resources :batches

  resources :clients do
    resources :addresses
    resources :phones
  end
  resources :payments
  # , except: [:edit]
  get "payments/new_with_contract/:contract_id", to: "payments#new", as: :new_with_contract

  root "home#index"

  get "client_results", to: "clients#results", as: :client_results
  get "all_notifications", to: "home#all_notifications"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/views/layouts/menu_partials/_footer.html.erb
<footer class="br-footer">
  <div class="footer-left">
    <!--
    <div class="mg-b-2">Copyright &copy; 2017-2022. Hector Alpuche Rodriguez. All Rights Reserved.</div>
    <div>Attentively and carefully made by ThemePixels, implemented by t0t0t4t0.</div>
  </div>
  -->
    <div class="footer-right d-flex align-items-center">
      <!--

      <span class="tx-uppercase mg-r-10">Share:</span>
     <a target="_blank" class="pd-x-5" href="https://www.facebook.com/sharer/sharer.php?u=http%3A//themepixels.me/bracket/intro"><i class="fa fa-facebook tx-20"></i></a>
<a target="_blank" class="pd-x-5" href="https://twitter.com/home?status=Bracket,%20your%20best%20choice%20for%20premium%20quality%20admin%20template%20from%20Bootstrap.%20Get%20it%20now%20at%20http%3A//themepixels.me/bracket/intro"><i class="fa fa-twitter tx-20"></i></a>
    <a target="" class="pd-x-5" href="#"><i class="fa fa-facebook tx-20"></i></a>
    <a target="" class="pd-x-5" href="#"><i class="fa fa-twitter tx-20"></i></a>
  -->
    </div>
  </footer>

app/views/layouts/menu_partials/_left_panel.html.erb
    <!-- ########## START: LEFT PANEL ########## -->
<div class="br-logo">   <%= link_to root_path, class: "" do %>
    <span>[</span>
    <span class="">R&R</span>
    <span>]</span>
  <% end %>
</div>
<div class="br-sideleft overflow-y-auto">
  <label class="sidebar-label pd-x-15 mg-t-20">Opciones</label>
  <div class="br-sideleft-menu">
    <%= link_to clients_path, class: "br-menu-link" do %>
      <div class="br-menu-item">
        <i class="menu-item-icon icon ion-person tx-24"></i>
        <span class="menu-item-label">Clientes</span>
      </div>
    <% end %>
    <%= link_to batches_path, class: "br-menu-link" do %>
      <div class="br-menu-item">
        <i class="menu-item-icon icon ion-pin tx-24"></i>
        <span class="menu-item-label">Lotes</span>
      </div>
    <% end %>
    <%= link_to contracts_path, class: "br-menu-link" do %>
      <div class="br-menu-item">
        <i class="menu-item-icon icon ion-filing tx-24"></i>
        <span class="menu-item-label">Contratos</span>
      </div>
    <% end %>
    <%= link_to payments_path, class: "br-menu-link" do %>
      <div class="br-menu-item">
        <i class="menu-item-icon icon fa fa-money tx-24"></i>
        <span class="menu-item-label">Pagos</span>
      </div>
    <% end %>
  </div>
  <!-- br-sideleft-menu -->
</div>
<!-- br-sideleft -->
<!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/menu_partials/_notification.html.erb
      <!-- loop starts here -->
<a href="" class="media-list-link read">
  <div class="media pd-x-20 pd-y-15">
    <%=link_to notification, class:"" do%>
      <div class="media-body">
        <p class="tx-13 mg-b-0 tx-gray-700"><strong class="tx-medium tx-gray-800"><%="ID del contrato: #{notification.id}"%> </strong></p>
        <p class="tx-13 mg-b-0 tx-gray-700"><strong class="tx-medium tx-gray-800"><%="Cliente: #{notification.client.first_name} #{notification.client.middle_name} #{notification.client.last_name}"%></strong></p>
        <span class="tx-12">Fecha del pago:&nbsp;
        </span><span class="tx 12 tx-danger"><%=notification.next_payment.strftime("%d-%m-%Y")%></span>
      </div>
    <% end %>
  </div>
  <!-- media -->
</a>

app/views/layouts/menu_partials/_notifications_panel.html.erb
      <!-- dropdown -->
<div class="dropdown">
  <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
    <i class="icon ion-ios-bell-outline tx-24"></i>
    <!-- start: if statement -->
    <% unless @notifications.empty? %>
      <span class="square-8 bg-danger pos-absolute t-15 r-5 rounded-circle"></span>
    <% end %>
    <!-- end: if statement -->
  </a>
  <div class="dropdown-menu dropdown-menu-header wd-300 pd-0-force">
    <div class="d-flex align-items-center justify-content-between pd-y-10 pd-x-20 bd-b bd-gray-200">
      <label class="tx-12 tx-info tx-uppercase tx-semibold tx-spacing-2">
        <%=@notifications.empty? ? "No hay pagos vencidos" : "Pagos vencidos"%>
      </label>
    </div>
    <!-- d-flex -->
    <div class="media-list">
      <% @notifications.each do |notification| %>
        <%=render "/layouts/menu_partials/notification", notification:notification%>
      <% end %>
    </div>
    <!-- media-list -->
    <div class="pd-y-10 tx-center bd-t">
  <%=link_to all_notifications_path, class:"tx-12" do%>
    <span>Mostrar todas las notificaciones</span>
    <i class="fa fa-angle-down mg-r-5"></i>
  <% end %>
</div>
  </div>
  <!-- dropdown-menu -->
</div>

app/views/layouts/menu_partials/_top_panel.html.erb
    <!-- ########## START: HEAD PANEL ########## -->
<div class="br-header">
  <div class="br-header-left">
    <div class="navicon-left hidden-md-down"><a id="btnLeftMenu" href=""><i class="icon ion-navicon-round"></i></a></div>
    <div class="navicon-left hidden-lg-up"><a id="btnLeftMenuMobile" href=""><i class="icon ion-navicon-round"></i></a></div>
  </div>
  <!-- br-header-left -->
  <div class="br-header-right d-flex align-items-center justify-content-between">
    <nav class="nav">
      <%=render "/layouts/menu_partials/notifications_panel"%>
      <!-- dropdown -->
      <div class="dropdown  d-flex justify-content-center align-items-center">
        <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
          <span class="logged-name hidden-md-down"><%=current_user.email%></span>
          <!--
          <span class="square-10 bg-success ml-5"></span>
          -->
        </a>
        <div class="dropdown-menu dropdown-menu-header wd-200">
          <ul class="list-unstyled user-profile-nav">
            <!--
            <li><a href=""><i class="icon ion-ios-person"></i> Edit Profile</a></li>
            <li><a href=""><i class="icon ion-ios-gear"></i> Settings</a></li>
            <li><a href=""><i class="icon ion-ios-download"></i> Downloads</a></li>
            <li><a href=""><i class="icon ion-ios-star"></i> Favorites</a></li>
            <li><a href=""><i class="icon ion-ios-folder"></i> Collections</a></li>
            -->
            <% if user_signed_in? %>
              <li>
                <%=button_to destroy_user_session_path, method: :delete, class:"btn btn-danger tx-bold" do%>
                  <span>Cerrar sesión </span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <!-- dropdown-menu -->
      </div>
      <!-- dropdown -->
    </nav>
    <%# <div class="navicon-right">
      <a id="btnRightMenu" href="" class="pos-relative">
        <i class="icon ion-ios-chatboxes-outline"></i>
        <!-- start: if statement -->
        <span class="square-8 bg-danger pos-absolute t-10 r--5 rounded-circle"></span>
        <!-- end: if statement -->
      </a>
    </div> %>
    <!-- navicon-right -->
  </div>
  <!-- br-header-right -->
</div>
<!-- br-header -->
<!-- ########## END: HEAD PANEL ########## -->