config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :contracts
  resources :batches

  resources :clients do
    resources :addresses
    resources :phones
  end
  resources :payments
  # , except: [:edit]
  get "payments/new_with_contract/:contract_id", to: "payments#new", as: :new_with_contract

  root "home#index"

  get "client_results", to: "clients#results", as: :client_results
  get "all_notifications", to: "home#all_notifications"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :contract

  validates :date, :file_number, :kind, :amount, :realization_date, presence: true

  scope :order_by_date, -> { order(date: :desc) }
  scope :order_by_realization_date, -> { order(realization_date: :desc) }
  scope :order_by_file_number, -> { order("file_number::integer asc") }
  scope :order_by_file_number_desc, -> { order("file_number::integer desc") }

  after_create :update_date
  before_destroy :subtract_next_payment

  def update_date
    if kind == "Completo" && file_number >= contract.payments.order_by_file_number.last.file_number
      current_date = contract.next_payment
      current_date += 1.month
      contract.update(next_payment: current_date)
    end
  end

  def subtract_next_payment
    if kind == "Completo" && file_number == contract.payments.order_by_file_number.last.file_number

      current_date = contract.next_payment
      current_date -= 1.month
      contract.update(next_payment: current_date)
    end
    # rescue => exception
    #   current_date = contract.first_payment
    #   contract.update(next_payment: current_date)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]
  before_action :set_catalogs, only: %i[new show update edit create destroy]

  # GET /payments or /payments.json
  def index
    @pagy, @payments = pagy(Payment.all.order_by_realization_date.order_by_date.order_by_file_number_desc)
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @payment.contract_id = params[:contract_id]
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to contract_path(@payment.contract), notice: "El pago fue registrado exitosamente." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "El pago fue actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to contract_path(@payment.contract), notice: "El pago fue eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  def set_catalogs
    @contracts = Contract.all
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:date, :file_number, :kind, :amount, :comments, :contract_id, :realization_date)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row mg-t-20 mb-4">
    <%= form.label "Cliente", style: "display: block", class:"col-sm-4 form-control-label" do%>
      Contrato
    <%end%>
    <!--<div class="col-sm-8 mg-t-10 mg-sm-t-0">
         <%= form.select :contract_id, @contracts.collect { |c| [ "Contrato de folio: #{c.id} - cliente: #{c.client.first_name} #{c.client.middle_name}", c.id ] }, {}, class:"form-control selectpicker border border-gray", :readonly => true%>
         </div>-->
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :contract_id, class:"form-control selectpicker border border-gray", :readonly => true%>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label "Cliente", style: "display: block" , class:"col-sm-4 form-control-label" do%>
      Cliente
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <div class="d-flex">
        <%= form.text_field "#{@payment.contract.client.first_name}", class:"form-control selectpicker border border-gray", :readonly => true, value:"#{@payment.contract.client.first_name} #{@payment.contract.client.middle_name} #{@payment.contract.client.last_name}"%>
      </div>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label "Fecha a la que corresponde", style: "display: block", class:"col-sm-4 form-control-label" do%>
      Fecha de realización <span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.date_field :realization_date, class:"form-control", value: DateTime.now.strftime("%m-%d-%Y") %>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label "Fecha a la que corresponde", style: "display: block", class:"col-sm-4 form-control-label" do%>
      Fecha a la que corresponde <span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.date_field :date, class:"form-control", value: payment.contract.nil? ? "" : payment.date ? payment.date : payment.contract.next_payment %>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label "Folio", style: "display: block" , class:"col-sm-4 form-control-label" do%>
      Folio<span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_field :file_number, class:"form-control", value: payment.contract.payments.empty? ? 1 : payment.contract.payments.order_by_file_number.last.file_number.to_i + 1 %>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label "Pago", style: "display: block" , class:"col-sm-4 form-control-label" do%>
      Pago<span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <div class="d-flex">
        <%= form.text_field :amount, class:"form-control"%>
      </div>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label "Tipo", style: "display: block" , class:"col-sm-4 form-control-label" do%>
      Tipo<span class="tx-danger">*</span>
    <% end %>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%=form.select :kind, options_for_select([["Completo"],["Abono"]]), {:prompt => ""}, class:"form-control selectpicker border border-gray"%>
    </div>
  </div>
  <div class="row mg-t-20">
    <%= form.label "Comentarios", style: "display: block" , class:"col-sm-4 form-control-label"%>
    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
      <%= form.text_area :comments, class:"form-control"%>
    </div>
  </div>
  <div class="row mg-t-10 d-flex justify-content-center">
    <div class="form-layout-footer mg-t-30 mt-2">
      <%= form.submit "Confirmar", :onclick => "return confirm('Desea resgistrar la información')", class:"btn btn-success"%>
    </div>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <div class="form-layout form-layout-7">
    <!-- row-->
    <div class="row no-gutters">
      <div class="col-5 col-sm-4">
        <span>Fecha de captura</span>
      </div>
      <div class="col-7 col-sm-8">
        <div class="form-control" >
          <%= payment.created_at.strftime("%d-%m-%Y")%>
        </div>
      </div>
    </div>
    <div class="row no-gutters">
      <div class="col-5 col-sm-4">
        <span>Fecha de realizacion</span>
      </div>
      <div class="col-7 col-sm-8">
        <div class="form-control" >
          <%= payment.realization_date.strftime("%d-%m-%Y")%>
        </div>
      </div>
    </div>
    <!-- row-->
    <div class="row no-gutters">
      <div class="col-5 col-sm-4">
        <span>Fecha a la que corresponde</span>
      </div>
      <div class="col-7 col-sm-8">
        <div class="form-control" >
          <%= payment.date.strftime("%d-%m-%Y")%>
        </div>
      </div>
    </div>
    <!-- row-->
    <!-- row-->
    <div class="row no-gutters">
      <div class="col-5 col-sm-4">
        <span>Folio</span>
      </div>
      <div class="col-7 col-sm-8">
        <div class="form-control" >
          <%= payment.file_number %>
        </div>
      </div>
    </div>
    <!-- row-->
    <div class="row no-gutters">
      <div class="col-5 col-sm-4">
        <span>Numero de contrato</span>
      </div>
      <div class="col-7 col-sm-8">
        <div class="form-control" >
          <%=link_to contract_path payment.contract do%>
            <span class="tx-bold"><%= payment.contract_id %></span>
          <% end %>
        </div>
      </div>
    </div>
    <!-- row-->
    <!-- row-->
    <div class="row no-gutters">
      <div class="col-5 col-sm-4">
        <span>Cliente</span>
      </div>
      <div class="col-7 col-sm-8">
        <div class="form-control" >
          <%=link_to client_path payment.contract.client do%>
            <%="#{payment.contract.client.first_name} #{payment.contract.client.middle_name} #{payment.contract.client.last_name}" %>
          <% end %>
        </div>
      </div>
    </div>
    <!-- row-->
    <!-- row-->
    <div class="row no-gutters">
      <div class="col-5 col-sm-4">
        <span>Monto</span>
      </div>
      <div class="col-7 col-sm-8">
        <div class="form-control" >
          <span class="tx-success tx-bold"><%=number_to_currency(payment.amount)%></span>
        </div>
      </div>
    </div>
    <!-- row-->
    <!-- row-->
    <div class="row no-gutters">
      <div class="col-5 col-sm-4">
        <span>Tipo</span>
      </div>
      <div class="col-7 col-sm-8">
        <div class="form-control" >
          <span class= <%=payment.kind=="Completo" ? "tx-success tx-bold" : "tx-warning tx-bold" %>>
          <%= payment.kind %>
          </span>
          </div>
        </div>
      </div>
      <!-- row-->
      <!-- row-->
      <div class="row no-gutters">
        <div class="col-5 col-sm-4">
          <span>Comentarios</span>
        </div>
        <div class="col-7 col-sm-8">
          <div class="form-control" >
            <%= payment.comments %>
          </div>
        </div>
      </div>
      <!-- row-->
    </div>

app/views/payments/_payment_index_table.html.erb
<td><%= payment.file_number%></td>
<% if payment.contract_id.nil? %>
  <td>
    <span class="tx-danger">No contract</span>
  </td>
  <td>
    <span class="tx-danger">No client</span>
  </td>
<% else %>
  <td>
    <%=link_to payment.contract do%>
      <span class="tx-bold"><%= payment.contract_id%></span>
    <% end %>
  </td>
  <td>
    <%=link_to payment.contract.client do%>
      <%="#{payment.contract.client.first_name} #{payment.contract.client.middle_name} #{payment.contract.client.last_name}" %>
    <% end %>
  </td>
  <td><%= payment.realization_date.nil? ? "No especificado" : payment.realization_date.strftime("%d-%m-%Y")%></td>
  <td><%= payment.date.strftime("%d-%m-%Y")%></td>
<% end %>
<td><span class=<%=payment.kind == "Completo" ? "tx-success tx-bold" : "tx-warning tx-bold "%>> <%=payment.kind%></span></td>
  <td><%=number_to_currency(payment.amount)%></td>
  <td class="d-flex align-items-top justify-content-center">
    <%= link_to payment, class:"btn btn-info" do%>
      <i class="fa fa-eye"></i>
      <span class="tx-white tx-bold"></span>
    <% end %>
    <!--
  <%= link_to edit_payment_path(payment), class:"btn btn-warning" do%>
    <i class="fa fa-pencil"></i>
  <% end %>
  -->
  </td>

app/views/payments/edit.html.erb
<div class="mg-t-80">
  <div class="col-xl-6">
    <div class="form-layout form-layout-4">
      <div class="pd-10 mg-t-20 bg-info mb-4 d-flex justify-content-between">
        <div class="nav nav-white-800 flex-column flex-md-row" role="tablist">
          <h6 class="tx-white m-2" >Edit Payment</h6>
        </div>
        <div>
          <%= link_to payments_path, class:"btn btn-primary" do%>
            <i class="fa fa-reply"></i>
          <% end %>
        </div>
      </div>
      <%= render "form", payment: @payment %>
    </div>
  </div>
  <!-- row -->
</div>
<br>

app/views/payments/index.html.erb
<div class="bd rounded pd-10">
  <h1 class="tx-bold d-flex justify-content-center">PAGOS</h1>
  <div class="row d-flex justify-content-end m-3">
    <!--
    <div class="d-flex align-items-center">
      <%= link_to new_payment_path, class:"btn btn-success tx-11 tx-uppercase tx-spacing tx-bold bd d-flex align-items-center pd-15" do%>
        <i class="fa fa-plus"></i>
      <% end %>
    </div>
  
  -->
  </div>
  <div id="batches" class="bd bd-gray-300 rounded table-responsive">
    <table class="table table-bordered mg-b-0">
      <thead>
        <tr>
          <th class="bg-info"><span class="tx-white">Folio</span></th>
          <th class="bg-info"><span class="tx-white">Contrato</span></th>
          <th class="bg-info"><span class="tx-white">Cliente</span></th>
          <th class="bg-info"><span class="tx-white">Fecha de realización</span></th>
          <th class="bg-info"><span class="tx-white">Fecha a la que corresponde</span></th>
          <th class="bg-info"><span class="tx-white">Tipo</span></th>
          <th class="bg-info"><span class="tx-white">Monto</span></th>
          <th class="bg-info"><span class="tx-white">Opciones</span></th>
        </tr>
      </thead>
      <tbody>
        <% @payments.each do |payment| %>
          <tr>
            <%=render "payments/payment_index_table", payment:payment %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <%=render "layouts/pagy/pagy"%>
  </div>
</div>

app/views/payments/new.html.erb
<div class="mg-t-80">
  <div class="col-xl-6">
    <div class="form-layout form-layout-4">
      <div class="pd-10 mg-t-20 bg-info mb-4 d-flex justify-content-between">
        <div class="nav nav-white-800 flex-column flex-md-row" role="tablist">
          <h6 class="tx-white m-2" >Nuevo Pago</h6>
        </div>
        <div>
          <%= link_to payments_path, class:"btn btn-primary" do%>
            <i class="fa fa-reply"></i>
          <% end %>
        </div>
      </div>
      <%= render "form", payment: @payment %>
    </div>
  </div>
  <!-- row -->
</div>
<br>

app/views/payments/show.html.erb
<div class="pd-10 mg-t-20 bg-info d-lg-flex justify-content-between">
  <div class="d-lg-flex align-items-center" role="tablist">
    <h5 class="tx-white m-2 tx-bold" >Informacion de pago</h5>
  </div>
  <div class="d-lg-flex">
    <div>
      <%= link_to payments_path, class:"btn btn-primary" do%>
        <i class="fa fa-reply"></i>
      <% end %>
    </div>
    <div class="btn-group ">
      <button type="button" class="btn btn-purple btn-block mg-b-10 dropdown-toggle tx-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-navicon"></i>
        <span class="tx-white">Opciones</span>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <!--
        <div class="dropdown-item">
          <%= link_to edit_payment_path(@payment), class:"" do%>
            <i class="fa fa-pencil"></i>
            <span class="tx-bold">Editar pago</span>
          <% end %>
        </div>
        -->
        <div class="dropdown-divider"></div>
        <div class="dropdown-item">
          <%= button_to @payment, method: :delete, :onclick => "return confirm('Desea eliminar este pago de manera permanente')", class:"btn btn-danger btn-block mg-b-10" do%>
            <i class="icon ion-close"></i>
            <span class="tx-bold">Eliminar</span>
          <% end %>
        </div >
      </div>
    </div>
  </div>
</div>
<%= render @payment %>
<br>